name: DryRun

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Help_test
      run: curl -s https://get.nextflow.io | bash && ./nextflow run poreCov.nf --help
    - name: fasta dry run
      run: |
          touch genome.fasta 
          ./nextflow run poreCov.nf --fasta genome.fasta -stub -profile stub --cores 2 --max_cores 2
    - name: fastq dry run
      run: |
          touch reads.fastq 
          ./nextflow run poreCov.nf --fastq reads.fastq -stub -profile stub --cores 2 --max_cores 2
    - name: fastq_pass dry run
      run: |
          mkdir fastq_pass 
          ./nextflow run poreCov.nf --fastq_pass fastq_pass/  -stub -profile stub --cores 2 --max_cores 2
    - name: fast5 dry run
      run: |
          mkdir fast5 
          ./nextflow run poreCov.nf --fast5 fast5/  -stub -profile stub --cores 2 --max_cores 2
