name: VariantCallingCI

on:
  push:
    branches: ["main", "master", "dev"]
  pull_request:
    branches: ["main", "master"]

jobs:
  VariantCallingCI:
    name: VariantCallingCI
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          channels: bioconda,conda-forge,defaults
          channel-priority: true
          auto-activate-base: true

      - name: Check conda installation
        run: |
          conda info

      - name: Install nextflow
        run: |
          conda install -c bioconda nextflow=21.04.0
          nextflow -version
      
      - name: Checkout CIEVaD
        uses: actions/checkout@v4
        with:
          repository: rki-mf1/cievad
          path: cievad
          ref: dev

      - name: Run CIEVaD hap
        run: |
          pushd cievad
          cp ../data/reference_nCov19/NC_045512.2.fasta .
          sed -i 's/>NC_045512.2 Severe acute respiratory syndrome coronavirus 2 isolate Wuhan-Hu-1, complete genome/>NC_045512.2/g' NC_045512.2.fasta
          nextflow run hap.nf -dsl2 -profile local,conda --reference NC_045512.2.fasta --read_type ont
          ls -la results/
          popd

      - name: Prep folder for poreCov
        run: |
          pushd cievad
          mkdir fastqs
          mv results/*.fastq fastqs/
          popd
  
      - name: Run poreCov
        run: |
          conda install -c conda-forge singularity
          nextflow run poreCov.nf -dsl2 --fastq cievad/fastqs/*.fastq -profile local,singularity --cores 2 --max_cores 4
          tree results

